apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hrmitra.fullname" . }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
