apiVersion: v1
kind: Service
metadata:
  name: {{ include "hrmitra.fullname" . }}-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "hrmitra.fullname" . }}-db
