apiVersion: v1
kind: Service
metadata:
  name: {{ include "hrmitra.fullname" . }}-web
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: {{ include "hrmitra.fullname" . }}-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | int }}
      targetPort: 3000
